package org.orion.avaya.servicetwo.model;

/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
@org.apache.avro.specific.AvroGenerated
public enum CallStatus implements org.apache.avro.generic.GenericEnumSymbol<CallStatus> {
    INVITED, ACTIVE, PROCESSED, CANCELED, ENDED, ERROR;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"org.orion.avaya.servicetwo.model.CallStatus\",\"symbols\":[\"INVITED\",\"ACTIVE\",\"PROCESSED\",\"CANCELED\",\"ENDED\",\"ERROR\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
